# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 120)
        MainWindow.setMinimumSize(QtCore.QSize(470, 120))
        MainWindow.setMaximumSize(QtCore.QSize(450, 120))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.general_frame = QtWidgets.QFrame(self.centralwidget)
        self.general_frame.setGeometry(QtCore.QRect(10, 10, 450, 100))
        self.general_frame.setMinimumSize(QtCore.QSize(450, 100))
        self.general_frame.setMaximumSize(QtCore.QSize(450, 100))
        self.general_frame.setStyleSheet("border-radius: 20px;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(203, 183, 196, 241), stop:1 rgba(0, 0, 209, 255));\n"
"border: 3px solid black;\n"
"")
        self.general_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.general_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.general_frame.setObjectName("general_frame")
        self.tBtn_closeWindow = QtWidgets.QToolButton(self.general_frame)
        self.tBtn_closeWindow.setGeometry(QtCore.QRect(400, 10, 45, 30))
        self.tBtn_closeWindow.setMinimumSize(QtCore.QSize(45, 30))
        self.tBtn_closeWindow.setMaximumSize(QtCore.QSize(45, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tBtn_closeWindow.setFont(font)
        self.tBtn_closeWindow.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(213, 63, 91);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: red;\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: rgb(184, 21, 32);\n"
"}")
        self.tBtn_closeWindow.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_closeWindow.setObjectName("tBtn_closeWindow")
        self.tBtn_minimaze = QtWidgets.QToolButton(self.general_frame)
        self.tBtn_minimaze.setGeometry(QtCore.QRect(350, 10, 45, 30))
        self.tBtn_minimaze.setMinimumSize(QtCore.QSize(45, 30))
        self.tBtn_minimaze.setMaximumSize(QtCore.QSize(45, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tBtn_minimaze.setFont(font)
        self.tBtn_minimaze.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(213, 63, 91);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: red;\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: rgb(184, 21, 32);\n"
"}")
        self.tBtn_minimaze.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_minimaze.setObjectName("tBtn_minimaze")
        self.lE_enter_username = QtWidgets.QLineEdit(self.general_frame)
        self.lE_enter_username.setGeometry(QtCore.QRect(15, 10, 280, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lE_enter_username.setFont(font)
        self.lE_enter_username.setStyleSheet("QLineEdit {\n"
"    border-radius: 15px;\n"
"    border: 1px solid black;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid black;\n"
"    background-color:  rgb(229, 229, 229);\n"
"}\n"
"")
        self.lE_enter_username.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lE_enter_username.setObjectName("lE_enter_username")
        self.btn_enter = QtWidgets.QPushButton(self.general_frame)
        self.btn_enter.setGeometry(QtCore.QRect(90, 50, 130, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_enter.setFont(font)
        self.btn_enter.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButtonn:hover {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(158, 158, 158);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 2px solid black;\n"
"    background-color: blue;\n"
"}")
        self.btn_enter.setObjectName("btn_enter")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tBtn_closeWindow.setText(_translate("MainWindow", "X"))
        self.tBtn_minimaze.setText(_translate("MainWindow", "_"))
        self.lE_enter_username.setPlaceholderText(_translate("MainWindow", "Введите ваше имя:"))
        self.btn_enter.setText(_translate("MainWindow", "Войти"))
