# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'english_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 420)
        MainWindow.setMinimumSize(QtCore.QSize(620, 420))
        MainWindow.setMaximumSize(QtCore.QSize(620, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.general_frame = QtWidgets.QFrame(self.centralwidget)
        self.general_frame.setGeometry(QtCore.QRect(10, 10, 600, 400))
        self.general_frame.setMinimumSize(QtCore.QSize(600, 400))
        self.general_frame.setMaximumSize(QtCore.QSize(600, 400))
        self.general_frame.setStyleSheet("border-radius: 20px;\n"
"background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 225, 255), stop:1 rgba(218, 218, 218, 255));\n"
"border: 3px solid black;\n"
"")
        self.general_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.general_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.general_frame.setObjectName("general_frame")
        self.tBtn_closeWindow = QtWidgets.QToolButton(self.general_frame)
        self.tBtn_closeWindow.setGeometry(QtCore.QRect(540, 10, 45, 30))
        self.tBtn_closeWindow.setMinimumSize(QtCore.QSize(45, 30))
        self.tBtn_closeWindow.setMaximumSize(QtCore.QSize(45, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tBtn_closeWindow.setFont(font)
        self.tBtn_closeWindow.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(213, 63, 91);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: red;\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: rgb(184, 21, 32);\n"
"}")
        self.tBtn_closeWindow.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_closeWindow.setObjectName("tBtn_closeWindow")
        self.tBtn_minimaze = QtWidgets.QToolButton(self.general_frame)
        self.tBtn_minimaze.setGeometry(QtCore.QRect(490, 10, 45, 30))
        self.tBtn_minimaze.setMinimumSize(QtCore.QSize(45, 30))
        self.tBtn_minimaze.setMaximumSize(QtCore.QSize(45, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tBtn_minimaze.setFont(font)
        self.tBtn_minimaze.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(213, 63, 91);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: red;\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: rgb(184, 21, 32);\n"
"}")
        self.tBtn_minimaze.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_minimaze.setObjectName("tBtn_minimaze")
        self.tBtn_first_word = QtWidgets.QToolButton(self.general_frame)
        self.tBtn_first_word.setGeometry(QtCore.QRect(15, 140, 260, 60))
        self.tBtn_first_word.setMinimumSize(QtCore.QSize(260, 60))
        self.tBtn_first_word.setMaximumSize(QtCore.QSize(260, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tBtn_first_word.setFont(font)
        self.tBtn_first_word.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(68, 68, 220);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(92, 130, 255);\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: blue;\n"
"}")
        self.tBtn_first_word.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_first_word.setObjectName("tBtn_first_word")
        self.label_word = QtWidgets.QLabel(self.general_frame)
        self.label_word.setGeometry(QtCore.QRect(130, 40, 340, 60))
        self.label_word.setMinimumSize(QtCore.QSize(340, 60))
        self.label_word.setMaximumSize(QtCore.QSize(340, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.label_word.setFont(font)
        self.label_word.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(110, 97, 255);\n"
"border: 3px solid black;\n"
"color: white;\n"
"")
        self.label_word.setAlignment(QtCore.Qt.AlignCenter)
        self.label_word.setObjectName("label_word")
        self.progressBar = QtWidgets.QProgressBar(self.general_frame)
        self.progressBar.setGeometry(QtCore.QRect(80, 340, 450, 40))
        self.progressBar.setMaximumSize(QtCore.QSize(450, 40))
        self.progressBar.setBaseSize(QtCore.QSize(450, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.142045 rgba(104, 46, 218, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.progressBar.setMaximum(10)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.label_count_word = QtWidgets.QLabel(self.general_frame)
        self.label_count_word.setGeometry(QtCore.QRect(15, 10, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.label_count_word.setFont(font)
        self.label_count_word.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(110, 97, 255);\n"
"border: 3px solid black;\n"
"color: white;\n"
"")
        self.label_count_word.setAlignment(QtCore.Qt.AlignCenter)
        self.label_count_word.setObjectName("label_count_word")
        self.tBtn_second_word = QtWidgets.QToolButton(self.general_frame)
        self.tBtn_second_word.setGeometry(QtCore.QRect(15, 230, 260, 60))
        self.tBtn_second_word.setMinimumSize(QtCore.QSize(260, 60))
        self.tBtn_second_word.setMaximumSize(QtCore.QSize(260, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tBtn_second_word.setFont(font)
        self.tBtn_second_word.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(68, 68, 220);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(92, 130, 255);\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: blue;\n"
"}")
        self.tBtn_second_word.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_second_word.setObjectName("tBtn_second_word")
        self.tBtn_third_word = QtWidgets.QToolButton(self.general_frame)
        self.tBtn_third_word.setGeometry(QtCore.QRect(325, 140, 260, 60))
        self.tBtn_third_word.setMinimumSize(QtCore.QSize(260, 60))
        self.tBtn_third_word.setMaximumSize(QtCore.QSize(260, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tBtn_third_word.setFont(font)
        self.tBtn_third_word.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(68, 68, 220);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(92, 130, 255);\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: blue;\n"
"}")
        self.tBtn_third_word.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_third_word.setObjectName("tBtn_third_word")
        self.tBtn_fourth_word = QtWidgets.QToolButton(self.general_frame)
        self.tBtn_fourth_word.setGeometry(QtCore.QRect(325, 230, 260, 60))
        self.tBtn_fourth_word.setMinimumSize(QtCore.QSize(260, 60))
        self.tBtn_fourth_word.setMaximumSize(QtCore.QSize(260, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tBtn_fourth_word.setFont(font)
        self.tBtn_fourth_word.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(68, 68, 220);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(92, 130, 255);\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: blue;\n"
"}")
        self.tBtn_fourth_word.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_fourth_word.setObjectName("tBtn_fourth_word")
        self.tBtn_load_file = QtWidgets.QToolButton(self.general_frame)
        self.tBtn_load_file.setGeometry(QtCore.QRect(540, 45, 45, 30))
        self.tBtn_load_file.setMinimumSize(QtCore.QSize(45, 30))
        self.tBtn_load_file.setMaximumSize(QtCore.QSize(45, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tBtn_load_file.setFont(font)
        self.tBtn_load_file.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(213, 63, 91);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: red;\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: rgb(184, 21, 32);\n"
"}")
        self.tBtn_load_file.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_load_file.setObjectName("tBtn_load_file")
        self.tBtn_voice = QtWidgets.QToolButton(self.general_frame)
        self.tBtn_voice.setGeometry(QtCore.QRect(277, 7, 50, 30))
        self.tBtn_voice.setMinimumSize(QtCore.QSize(50, 30))
        self.tBtn_voice.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tBtn_voice.setFont(font)
        self.tBtn_voice.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(68, 68, 220);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(92, 130, 255);\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: blue;\n"
"}")
        self.tBtn_voice.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_voice.setObjectName("tBtn_voice")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tBtn_closeWindow.setText(_translate("MainWindow", "X"))
        self.tBtn_minimaze.setText(_translate("MainWindow", "_"))
        self.tBtn_first_word.setText(_translate("MainWindow", "WORD"))
        self.label_word.setText(_translate("MainWindow", "WORD"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.label_count_word.setText(_translate("MainWindow", "0"))
        self.tBtn_second_word.setText(_translate("MainWindow", "WORD"))
        self.tBtn_third_word.setText(_translate("MainWindow", "WORD"))
        self.tBtn_fourth_word.setText(_translate("MainWindow", "WORD"))
        self.tBtn_load_file.setText(_translate("MainWindow", ""))
        self.tBtn_voice.setText(_translate("MainWindow", ""))
